### ISSUE TITLE
Problem when opening mail with Teams invite

### ISSUE THREAD

**Issue by Hallikas** [texxasrulez/old_calendar#3]
First I did tried that older version, installed with:
composer -n require roundcube/carddav:3.0.3 texxasrulez/calendar:~0.0.6.0 sabre/vobject:~3.4

Will get installed nicely, and it works, Also that mail with invite works.

But when I update to latest:
composer -n require roundcube/carddav:4.0.0-alpha1 texxasrulez/calendar:~0.0.7.0 guzzlehttp/guzzle:~7.0

I can't open that mail with teams invite. PHP gets error:
HP message: PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /data/www/roundcube.test/plugins/calendar/calendar.php:3191
Stack trace:
#0 /data/www/roundcube.test/program/lib/Roundcube/rcube_plugin_api.php(472): calendar->mail_messagebody_html(Array)
#1 /data/www/roundcube.test/program/include/rcmail_output_html.php(1490): rcube_plugin_api->exec_hook('template_object...', Array)
#2 [internal function]: rcmail_output_html->xml_command(Array)
#3 /data/www/roundcube.test/program/include/rcmail_output_html.php(1224): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#4 /data/www/roundcube.test/program/include/rcmail_output_html.php(782): rcmail_output_html->parse_xml('<roundcube:obje...')
#5 /data/www/roundcube.test/program/include/rcmail_output_html.php(615): rcmail_output_html->parse('message', false)
#6 /data/www/roundcube.test/program/steps/mail/show.inc(177): rcmail_output_html->send('message', false)
#7 /data/www/roundcube.test/index.php(311): includ" while reading response header

3191 line is:
        $date     = new DateTime($event['start']->format('Y-m-d') . ' 12:00:00', new DateTimeZone('UTC'));

I did look into that '$event' array. It does not contain 'start' key. Meeting date is introduced in:
    [changed] => DateTimeImmutable Object
        (
            [date] => 2020-09-01 07:15:54.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

**Comment by texxasrulez** [comment]
I have ran into some things recently. Long story short, I will be homeless in 3 weeks, so I may or may not get to this

**Comment by Hallikas** [comment]
> I have ran into some things recently. Long story short, I will be homeless in 3 weeks, so I may or may not get to this

I'm so sorry to hear that. I hope that everything solves out soon, in good way for you.

**Comment by METEO64** [comment]
Hi,
Did you fixe it?

Here is my problem :

[01-Jan-2021 13:49:56 Europe/Brussels] PHP Fatal error:  Uncaught Error: Call to a member function edit_event() on null in /volume1/web/Roundcube/plugins/calendar/calendar.php:3480
Stack trace:
#0 /volume1/web/Roundcube/program/lib/Roundcube/rcube_plugin_api.php(494): calendar->mail_import_itip()
#1 /volume1/web/Roundcube/index.php(294): rcube_plugin_api->exec_action('calendar.mailim...')
#2 {main}
  thrown in /volume1/web/Roundcube/plugins/calendar/calendar.php on line 3480
